### ISSUE TITLE
feat: 약속 참여자 상태 목록 조회

### ISSUE THREAD

**Issue by kimhm0728** [woowacourse-teams/2024-ody#238]
# 📝 작업 내용
BE
- [x] #234 @coli-geonwoo @hyeon0208
- [x] #226 @coli-geonwoo @hyeon0208

AN
- [x] #205 @haeum808 @kimhm0728 
- [x] #207 @haeum808 @kimhm0728

**Comment by hyeon0208** [comment]
콜리와 함께 오늘 안에 문서화 작업 마쳐놓겠습니다 👍🏻

**Comment by hyeon0208** [comment]
@kimhm0728 약속 참여자 상태 목록 조회 API 문서화 PR은 요청했고 머지되면 반영될꺼 같아요 ~!

**Comment by kimhm0728** [comment]
@hyeon0208 @coli-geonwoo 
eta 관련 api 연결했고 merge까지 됐습니다. 스케줄링/폴링 요 부분 기능 구현은 다 했는데, 내일 오전 안에 리팩터링하고 PR 올릴 수 있을 것 같아요!

**Comment by kimhm0728** [comment]
@hyeon0208 @coli-geonwoo 폴링, 스케줄링, api 연결 모두 구현 완료! 머지 완료!

**Comment by hyeon0208** [comment]
@kimhm0728 
저희도 기능 개발은 완료 됐고
오늘 QA 할 수 있도록 시작하기전에 merge할 예정입니다 👍
근데 충돌 해결 하면서 로컬 커밋 내역은 백엔드 코드만 커밋 됐지만 PR 커밋 상에서는 안드로이드 코드가 변경사항으로 들어가있는
문제가 있어서 오늘 스크럼때 이야기 한번 해봐야할꺼같아요 😭
