### ISSUE TITLE
feat: 약속 개설

### ISSUE THREAD

**Issue by kimhm0728** [woowacourse-teams/2024-ody#239]
# 📝 작업 내용
BE
- [x] #230 

AN
- [x] #198

**Comment by coli-geonwoo** [comment]
@kimhm0728 

약속 개설 API 문서화 및 구현 완료 후, merge 되었습니다.
이제 Swagger에서 /v1/meetings 활용 가능합니다.

**Comment by kimhm0728** [comment]
@coli-geonwoo 
오 빠른 구현 감사합니다 👍 
저는 내일 중으로 모임 개설/참여 모두 개발 완료될 것 같아요. merge까지 다 끝나면 이 이슈에 멘션 드릴게요~!

**Comment by kimhm0728** [comment]
@coli-geonwoo 
약속 개설, 참여 모두 개발 완료하여 PR 올렸습니다. merge되면 말씀드릴게요!
그런데 스웨거 상으로는 응답 데이터 중 `time`이 `HH:mm` 형태인데, 실제로 응답이 오는 데이터는 `HH:mm:ss` 형태더라구요.
콜리가 개발한 `v1/meetings` 뿐만 아니라 `v1/mates`, `meetings/me` 등 `time`이 있는 데이터들은 대부분 그런 것 같아요. 내일 오프라인으로 백엔드 팀원들에게 다시 한 번 말해보겠습니다!

**Comment by kimhm0728** [comment]
약속 개설, 참여 merge되었는데 코멘트 남기는 걸 깜빡했네요.. ㅎㅎ
혹시 문서화 말고 구현도 완료되었나요?? 그럼 내일 같이 맞춰보면 좋을 것 같아요.
