### ISSUE TITLE
feat: 약속 참여

### ISSUE THREAD

**Issue by kimhm0728** [woowacourse-teams/2024-ody#240]
# 📝 작업 내용
BE
- [x] #231

AN
- [x] #198

**Comment by hyeon0208** [comment]
토요일 안에 문서화 작업 마쳐놓겠습니다 ~!

**Comment by hyeon0208** [comment]
문서 작업은 마쳤고 merge후에 반영될 것 같아요 
근데 주말이라 언제 리뷰를 해줄지 모르겠네요 🤔

+ 궁금한 점
현재 오디 노션에 있는 개설과 참여가 분리된 `v1` API 문서 에서는
현재 개설하고 참여해 로그 화면이 보이기 까지 요청 흐름이 
/v1/meetings -> /v1/mates -> /meetings/{meetingId}/noti-log + /v1/meetings/{meetingId} 요청 순이 되는 것 같은데 맞나요? 
맞다면, /v1/mates 요청에 대한 응답 데이터 중 view 화면을 그리는데 사용되지 않는 데이터가 많은 것 같아 질문 드립니다 🙇🏼‍♂️

**Comment by kimhm0728** [comment]
@hyeon0208 
빠른 문서 작업 감사합니다~!!! 👍

카키가 말씀하신 요청 흐름 맞아요!
2차 스프린트까지는 /mates의 응답 데이터로 바로 뷰를 그렸었는데요. 현재는 약속 단건 조회 api가 있으니, /v1/mates 응답 데이터로는 약속 id 정도만 줘도 될 것 같긴합니다.

**Comment by hyeon0208** [comment]
@kimhm0728 
분리하는 작업에서 기존 응답 그대로 가져간다면 코드가 가독성이 좋지 못해지는 것 같아 질문드렸는데 빠른 답변 감사합니다 😃
그렇다면 혹시 모르니 /v1/mates 요청에 대한 응답으로 의미가 없어보이는 "참여자 리스트, 참여자 닉네임"을 제외한 데이터들을 보내도록 해볼게요
view 작업하시면서 문제가 있다면 말씀해주세요 🙏🏻

**Comment by hyeon0208** [comment]
@kimhm0728
약속 참여 API 문서 merge, 배포 완료

이전에 코멘트로 말한 불필요한 데이터는 기능 개발 PR이 머지되면 문서상에서 지워질 꺼같아요 😄

**Comment by kimhm0728** [comment]
@hyeon0208 
오! 저도 응답 데이터가 줄어들면 불필요한 dto를 선언하지 않아도 돼서 넘 좋습니다 👍 주말에도 백엔드는 열일하는군요... ㅋㅋ
저는 약속 개설, 참여를 동시에 작업해야할 것 같아서, `약속 개설 api 문서화`도 모두 merge가 되면 개발 시작하겠습니다!
개발 완료되거나 궁금한 점이 생기면 이 이슈에 다시 코멘트 드릴게요~!

**Comment by kimhm0728** [comment]
@hyeon0208 
약속 개설, 참여 모두 개발 완료하여 PR 올렸습니다. merge되면 말씀드릴게요!
그런데 스웨거 상으로는 응답 데이터 중 `time`이 `HH:mm` 형태인데, 실제로 응답이 오는 데이터는 `HH:mm:ss` 형태더라구요.
카키가 개발한 `v1/mates` 뿐만 아니라 `v1/meetings`, `meetings/me` 등 `time`이 있는 데이터들은 대부분 그런 것 같아요. 내일 오프라인으로 백엔드 팀원들에게 다시 한 번 말해보겠습니다!
