### ISSUE TITLE
feat: 안드로이드 기초세팅

### ISSUE THREAD

**Issue by haeum808** [woowacourse-teams/2024-ody#4]
# 📝 작업 내용
- [x] retrofit service
- [x] styles.xml
- [x] dimens.xml
- [x] color.xml
- [x] radius.xml
- [x] ktlint
- [x] font
- [x] 화면 회전 막기
- [x] 권한(manifest.xml)
  - [x] 인터넷
  - [x] 알림 
- [x] 다크테마 금지
- [x] 액션바 제거
- [x] 패키지 구조
- [x] 필요한 의존성들 추가
- [x] gitignore 파일 설정

**Comment by kimhm0728** [comment]
안드로이드 각자 설정할 것
- ktLint 프리커밋 훅
- 와일드카드 import 설정

**Comment by aprilgom** [comment]
수고하셨습니다!
